---
radius_server_host: 52.192.214.252
radius_server_secret: vpnsupersecretkey
dns_servers:
  - 172.31.30.104
  - 8.8.8.8
ipsec_enable_ikev1: false
ipsec_enable_ikev2: false
ipsec_enable_l2tp: true
ipsec_psk: vpnsupersecretkey
ipsec_use_radius: true
ipsec_dns_servers: "{{ dns_servers }}"
ipsecradius_host: 52.192.214.252
ipsecradius_secret: vpnsupersecretkey
l2tp_server_name: "Wyvernsquare Staging"
l2tp_network:
  local_ip: 172.31.27.1
  remote_ip: 172.31.27.10-249
  subnet: 172.31.27.0/24
l2tp_dns_servers: "{{ dns_servers }}"
l2tp_use_radius: true
l2tpradius_host: 52.192.214.252
l2tpradius_secret: vpnsupersecretkey
l2tp_enable_nat: true
l2tp_under_ipsec: true
pptp_server_name: "Wyvernsquare Staging"
pptp_network:
  local_ip: 172.31.27.1
  remote_ip: 172.31.27.10-249
  subnet: 172.31.27.0/24
pptp_dns_servers: "{{ dns_servers }}"
pptp_use_radius: true
pptpradius_host: 52.192.214.252
pptpradius_secret: vpnsupersecretkey
