---
# This playbook runs pre scripts 
# necessary for initial setups
# before running follow-up scripts

# Scripts that need to be run in the initial phase of server provisioning

- name: Create new forest and promote dc1 to domain controller
  gather_facts: true
  tasks:
    - name: Configure Internal Network settings
      script: ./ps-scripts/Set-IntnetSettings.ps1
    - name: Create New Forest and Domain Controller
      script: "./ps-scripts/Create-NewDomain.ps1 -u {{ username }} -p {{ password }}"
      ignore_errors: yes
    - name: Restart Machine 
      script: ./ps-scripts/shutdown.ps1
      ignore_errors: yes
    - pause: minutes=7
    - name: Re-configure DNS address because promoted DC loses DNS config
      script: ./ps-scripts/Set-IntnetSettings.ps1
      ignore_errors: yes

- name: Promote dc2 to domain controller
  hosts: dc2
  gather_facts: true
  tasks:
    - name: Configure Internal Network settings
      script: ./ps-scripts/Set-IntnetSettings.ps1
    - name: Join domain script
      script: "./ps-scripts/client-djoin.ps1 -u {{ username }} -p {{ password }}"
      ignore_errors: true
    - name: Restart Machine 
      script: ./ps-scripts/shutdown.ps1
      ignore_errors: yes
    - pause: minutes=3
    - name: Promote to Domain Controller
      script: "./ps-scripts/Promote-DC.ps1 -u {{ username }} -p {{ password }}"
      ignore_errors: yes
    - name: Restart Machine 
      script: ./ps-scripts/shutdown.ps1
      ignore_errors: yes
    - pause: minutes=5
- name: Configure other servers
  hosts: wsus
  gather_facts: true
  tasks:
    - name: Configure Internal Network settings
      script: ./ps-scripts/Set-IntnetSettings.ps1
    - name: Join domain script
      script: "./ps-scripts/client-djoin.ps1 -u {{ username }} -p {{ password }}"
      ignore_errors: yes
    - name: Restart Machine
      script: ./ps-scripts/shutdown.ps1
      ignore_errors: yes
    - pause: minutes=3