#see group_vars/vpn.yml.example for configuration options
---
- hosts: vpn1
  sudo: yes
  user: vagrant
  roles:
    - role: ppp-radiusclient
      device_type: pptp
    - role: ppp-radiusclient
      device_type: l2tp
    - strongswan
    - l2tp
    - nat

