# Joins a server to the domain

- name: Join domain script
  script: "../../../ps-scripts/client-djoin.ps1 -u {{ username }} -p {{ password }} -d {{ domain }}"
- name: Reboot
  win_reboot:
- name: waiting for server to come back
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 5985
    delay: 10
    timeout: 500
    state: started
