---
#auto generate ikev2 certs
#
- name: init ca
  sudo: yes
  shell: ipsec pki --gen --outform pem > /etc/strongswan/ipsec.d/private/ca_key.pem
         creates=/etc/strongswan/ipsec.d/private/ca_key.pem
  notify: restart ipsec
  tags:
    - ipsec
    - ca

- name: create ca cert
  sudo: yes
  shell: ipsec pki --self --in /etc/strongswan/ipsec.d/private/ca_key.pem --dn "C=CH, O=vpndeploy, CN={{ ipsec_ca_common_name }}" --ca --outform pem > /etc/strongswan/ipsec.d/cacerts/ca_cert.pem
         creates=/etc/strongswan/ipsec.d/cacerts/ca_cert.pem
  notify: restart ipsec
  tags:
    - ipsec
    - ca

- name: create server key
  sudo: yes
  shell: ipsec pki --gen --outform pem > /etc/strongswan/ipsec.d/private/server_key.pem
         creates=/etc/strongswan/ipsec.d/private/server_key.pem
  notify: restart ipsec
  tags:
    - ipsec
    - ca

- name: create server cert
  sudo: yes
  shell: ipsec pki --pub --in /etc/strongswan/ipsec.d/private/server_key.pem | ipsec pki --issue --cacert /etc/strongswan/ipsec.d/cacerts/ca_cert.pem --cakey /etc/strongswan/ipsec.d/private/ca_key.pem --dn "C=CH,O=vpndeploy,CN={{ ipsec_domain }}" --san="{{ ipsec_domain }}" --flag serverAuth --flag ikeIntermediate --outform pem > /etc/strongswan/ipsec.d/certs/server_cert.pem
         creates=/etc/strongswan/ipsec.d/certs/server_cert.pem
  notify: restart ipsec
  tags:
    - ipsec
    - ca
