---
#install common packages

- name: update yum cache
  action: yum update_cache=yes cache_valid_time=3600
  tags:
    - common
    - update

- name: install editor
  action: yum pkg={{ item }} state=installed
  with_items:
    - vim
  tags:
    - common
    - editor

- name: install net-tools
  yum: name=net-tools state=installed

- name: install version control tools
  action: yum pkg={{ item }} state=installed
  with_items:
    - git
  tags:
    - common
    - vcs

- name: install common python packages
  action: yum pkg={{ item }} state=installed
  with_items:
    - python-setuptools
    - python-pip
    - python-dev
    - python-pycurl
  tags:
    - common
    - python


- name: install supervisor
  action: yum pkg={{ item }} state=installed
  with_items:
    - supervisor
  tags:
    - common
    - python
    - supervisor

- name: install virtualenv
  action: pip name={{ item }} state=present
  with_items:
    - virtualenv
  tags:
    - common
    - python
