---
# Creates Forest and Domain, and set as Primary Domain Controller 

- name: Create New Forest and Domain Controller
  script: "../../../ps-scripts/Create-NewDomain.ps1 -u {{ username }} -p {{ password }} -d {{ domain }}"
  ignore_errors: yes
- name: Restart Machine 
  script: ../../../ps-scripts/restart.ps1
  ignore_errors: yes
- pause: minutes=7