---
# Creates Forest and Domain, and set as Primary Domain Controller 

- name: Install Domain Controller Role
  win_feature:
    name: "AD-Domain-Services"
    state: present
    restart: yes
    include_sub_feature: yes
    include_management_tools: yes
- name: Create New Forest and Domain Controller
  script: "../../../ps-scripts/Create-NewDomain.ps1 -u {{ username }} -p {{ password }} -d {{ domain }}"
  ignore_errors: yes
- name: Restart Machine 
  win_reboot:
- name: waiting for server to come back
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 5985
    delay: 10
    timeout: 500
    state: started

- include: resolvepw.yml

