- name: Configure DHCP Server Role
  script: "../../../ps-scripts/Configure-DHCPServer.ps1 -gw {{ gw }} -dns {{ dns }} -netmask {{ netmask }} -masklength {{ masklength }} -svrstart {{ svrstart }} -svrend {{ svrend }} -domain {{ domain }}"
