---
# Sets up a server as Windows Server Update Services
- name: Install and Configure WSUS
  script: ../../../ps-scripts/configure-wsus.ps1
- name: Restart Machine
  win_reboot:
- name: waiting for server to come back
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 5985
    delay: 10
    timeout: 500
    state: started
