---
#RadiusClient for PPP 

- name:  Enforce radiusclient is installed
  package: name={{ item }} state=latest
  with_items:
    - radiusclient-ng.x86_64
    - radiusclient-ng-devel.x86_64
    - radiusclient-ng-utils.x86_64
  tags: radius

- debug:
    msg: " {{ device_type }} "
- debug:
    msg: " {{ radius_servers }} "
- debug:
    msg: " {{ radius_servers.host }} "
- debug:
    msg: " {{ radius_servers.secret }} "

- name:   upload radiusclient config for pptp
  action: template src=etc/radiusclient/{{ item }}
                    dest=/etc/radiusclient/{{ device_type }}-{{ item }}
                    owner=root group=root mode=0644
  with_items:
    - radiusclient.conf
    - servers
    - dictionary
  tags: radius

- name: fix can't resolve own hostname problem  - hostname
  lineinfile: dest=/etc/hosts 
              line="{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
              regexp="{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
              state=present

- name: fix can't resolve own hostname problem - fqdn 
  lineinfile: dest=/etc/hosts 
              line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }}"
              regexp="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }}"
              state=present
