- name: Run Sysprep to generalize Server SID
  raw: 'C:\Windows\System32\Sysprep\sysprep.exe /generalize /oobe /reboot'
- name: Restart Machine
  script: ../../../ps-scripts/restart.ps1
  ignore_errors: yes
- name: waiting for server to come back
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 5985
    delay: 10
    timeout: 500
    state: started
