---
l2tp_server_name: "{{l2tp_server_name}}"

l2tp_network: "{{l2tp_network}}"

l2tp_dns_servers: "{{dns_servers}}"

l2tp_mtu: 1340

l2tp_use_radius: false
l2tp_radius_servers:
  - host: "{{l2tpradius_host}}"
    secret: "{{l2tpradius_secret}}"

l2tp_enable_nat: "{{l2tp_enable_nat}}"
l2tp_under_ipsec: "{{l2tp_under_ipsec}}"

l2tp_users: []

#l2tp_users:
#  - username: "user1"
#    password: "pass1"
#  - username: "user2"
#    password: "passw"
